baseURL = "https://www.yannhoffmann.com/"
languageCode = "en-us"
title = "My Blog"
DefaultContentLanguage= "en"
enableInlineShortcodes = true
summarylength = 10
enableEmoji = true
paginate = 6
theme = "soho"
# Too many requests instagram
ignoreErrors = ["error-remote-getjson"]

disqusShortname = "yhoffmann"
googleAnalytics = "G-FY2118S7T9"

[params]
title = "A Computer Scientist's blog"
author = "Yann Hoffmann"
description = "My Blog"
tagline = "trestsetest"

profilePicture = "images/profile.png"
copyright = "Yann Hoffmann"
license = "CC BY-SA 4.0"
builtWith = false
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
mainSections = ["post"]

## Set side bar color
themeColor = "#5E81AC"

#customCss = ["css/blog.css"]
#customJs = ["js/blog.js"]

  ## Set as many as you want.
    [[params.socialIcons]]
    icon = "fa-linkedin"
    title = "Linkedin"
    url = "https://www.linkedin.com/in/yann-hoffmaaann/"

    [[params.socialIcons]]
    icon = "fa-github"
    title = "GitHub"
    url = "https://github.com/Yann21"


[menu]
    [[menu.main]]
    name = "Archive"
    weight = 100
    identifier = "posts"
    url = "/posts/"

    [[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"

    [[menu.main]]
    name = "Contact"
    identifier = "contact"
    weight = 400
    url = "/contact/"


[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"


[markup]
    [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true # if false, you need to provide you own custom CSS
    style = "monokai"
    tabWidth = 4

[deployment]
order = [".jpg$", ".gif$"]

[[deployment.targets]]
name = "deployment"
URL = "s3://www.yannhoffmann.com?region=eu-central-1"
exclude = ".git/*"
